### ISSUE TITLE
[WIP] Mock "scenarios"

### ISSUE THREAD

**Issue by ldesgoui** [ldesgoui/discord_game_sdk#1]
Currently, the `mock` library accepts all calls but does nothing with most, I could keep implementing simple results, hardcoded data etc, or I could go all in and let the developer describe the current state of Discord, such as which Users are registered, etc.
This description would live in a `.toml` file, the path would be pointed at by an environment variable and it would be read when `DiscordCreate` is called.

This would take more development time but it also would allow me to work on the bindings using Linux even more, which is always a welcome privilege.

Please let me know what you think about this.

**Comment by ldesgoui** [comment]
Something like this:

```toml
user_id = 1
user_flags = ["Partner"]
user_premium = "Tier2"


[[ users ]]
id = 1
username = "One"
discriminant = "0001"
avatar_path = "./avatar.png"

[[ users ]]
id = 2
username = "Two"
discriminant = "0002"
avatar_path = "./avatar.png"
relationship = "friend"
status = "idle"

[[ users ]]
id = 3
username = "Tres"
discriminant = "0003"
avatar_path = "./avatar.png"
relationship = "pending_outgoing"
status = "offline"


[[ events ]]
after = 3
event = "current_user_update"
username = "Liquid | One"

[[ events ]]
after = 5
event = "relationship_update"
id = 3
relationship = "friend"
```
